D_norm_type: batch
E_norm_type: bn
G_norm_type: in
batch_size: 4
beta1: 0.5
beta2: 0.999
crop: true
crop_size: 256
dataset_dir: ../data
dims: 2048
downs_num: 3
epoch_init_lr: 500
epoch_start: 1
flip: true
gamma: 0.5
gan_mode: hinge
input_nc: 3
inst_size: 64
is_train: true
lambda_L1: 1
lambda_feat: 10
lambda_gan: 1
lambda_vgg: 10
lr: 0.0002
lr_policy: linear
mask_nc: 1
mask_rate: 0.5
max_epoch: 60
max_num: 180
n_layers_D: 3
ndf: 64
nef: 64
ngf: 32
niter_decay: 1500
no_ganFeat_loss: false
no_vgg_loss: false
num_D: 3
ori_size: 16
output_nc: 3
print_loss_freq: 10
results_root: results/
save_epoch_freq: 10
shuffle: true
step_size: 50
style_dim: 256
test_batch_size: 4
test_freq: 5
use_dropout: false
visual_img_freq: 8000
weight_decay: 0.0001
worker: 2
